**Introdução ao Numpy**

In [16]:
import numpy as np
matriz = np.array([[1,2,3],[4,5,6]])
matriz

array([[1, 2, 3],
       [4, 5, 6]])

**Tipos**

In [17]:
type(matriz)

numpy.ndarray

In [18]:
matriz.dtype.name

'int32'

**Dimenções do DataFrame**

In [19]:
matriz.shape

(2, 3)

In [21]:
matriz.size

6

**Criando Valores (passo a passo, espaçados ou randômicos)

In [22]:
np.arange(0,30,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [24]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [29]:
np.random.randint(0,30,6)

array([10,  9,  6, 24, 16,  4])

In [31]:
matriz2 = np.random.randint(0,30,6) .reshape(3,2)
matriz2

array([[ 1, 29],
       [ 2, 29],
       [28,  0]])

In [32]:
matriz.max()

6

In [34]:
matriz.argmax()

5

In [ ]:
matriz